name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: ["kind/bug" , "needs-triage"]
projects: ["konveyor/67"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  attributes:
    label: Konveyor version
    description: What is the Konveyor version you're using?
  validations:
    required: true
- type: dropdown
  id: priority
  attributes:
    label: Priority
    description: What is the prority of this bug?
    options:
      - Critical
      - Blocker
      - Major
      - Minor
      - Undefined (Default)
    default: 0
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: dropdown
  id: how_reproducible 
  attributes:
    label: How Reproducible
    description: How often the bug can be reproduced?
    options:
      - Always (Default)
      - Sometimes
      - Never
      - Other (Add more details in 'Anything else')
    default: 0
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **Analyzer Image SHA** 
        - **JDTLS  base image SHA**
        - **Provider Settings JSON**
    value: |
        - **Analyzer Image SHA** 
        - **JDTLS  base image SHA**
        - **Provider Settings JSON**
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
