// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: provider/internal/grpc/library.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Capability struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TemplateContext *structpb.Struct       `protobuf:"bytes,2,opt,name=templateContext,proto3" json:"templateContext,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{0}
}

func (x *Capability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Capability) GetTemplateContext() *structpb.Struct {
	if x != nil {
		return x.TemplateContext
	}
	return nil
}

type Config struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Location               string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	DependencyPath         string                 `protobuf:"bytes,2,opt,name=dependencyPath,proto3" json:"dependencyPath,omitempty"`
	AnalysisMode           string                 `protobuf:"bytes,4,opt,name=analysisMode,proto3" json:"analysisMode,omitempty"`
	ProviderSpecificConfig *structpb.Struct       `protobuf:"bytes,5,opt,name=providerSpecificConfig,proto3" json:"providerSpecificConfig,omitempty"`
	Proxy                  *Proxy                 `protobuf:"bytes,6,opt,name=proxy,proto3" json:"proxy,omitempty"`
	LanguageServerPipe     string                 `protobuf:"bytes,7,opt,name=languageServerPipe,proto3" json:"languageServerPipe,omitempty"`
	Initialized            bool                   `protobuf:"varint,8,opt,name=initialized,proto3" json:"initialized,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Config) GetDependencyPath() string {
	if x != nil {
		return x.DependencyPath
	}
	return ""
}

func (x *Config) GetAnalysisMode() string {
	if x != nil {
		return x.AnalysisMode
	}
	return ""
}

func (x *Config) GetProviderSpecificConfig() *structpb.Struct {
	if x != nil {
		return x.ProviderSpecificConfig
	}
	return nil
}

func (x *Config) GetProxy() *Proxy {
	if x != nil {
		return x.Proxy
	}
	return nil
}

func (x *Config) GetLanguageServerPipe() string {
	if x != nil {
		return x.LanguageServerPipe
	}
	return ""
}

func (x *Config) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Successful    bool                   `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	BuiltinConfig *Config                `protobuf:"bytes,4,opt,name=builtinConfig,proto3" json:"builtinConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{2}
}

func (x *InitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InitResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *InitResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InitResponse) GetBuiltinConfig() *Config {
	if x != nil {
		return x.BuiltinConfig
	}
	return nil
}

type ExternalLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalLink) Reset() {
	*x = ExternalLink{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalLink) ProtoMessage() {}

func (x *ExternalLink) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalLink.ProtoReflect.Descriptor instead.
func (*ExternalLink) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{3}
}

func (x *ExternalLink) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExternalLink) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          float64                `protobuf:"fixed64,1,opt,name=line,proto3" json:"line,omitempty"`
	Character     float64                `protobuf:"fixed64,2,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{4}
}

func (x *Position) GetLine() float64 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Position) GetCharacter() float64 {
	if x != nil {
		return x.Character
	}
	return 0
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartPosition *Position              `protobuf:"bytes,1,opt,name=startPosition,proto3" json:"startPosition,omitempty"`
	EndPosition   *Position              `protobuf:"bytes,2,opt,name=endPosition,proto3" json:"endPosition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{5}
}

func (x *Location) GetStartPosition() *Position {
	if x != nil {
		return x.StartPosition
	}
	return nil
}

func (x *Location) GetEndPosition() *Position {
	if x != nil {
		return x.EndPosition
	}
	return nil
}

type IncidentContext struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FileURI              string                 `protobuf:"bytes,1,opt,name=fileURI,proto3" json:"fileURI,omitempty"`
	Effort               *int64                 `protobuf:"varint,2,opt,name=Effort,proto3,oneof" json:"Effort,omitempty"`
	CodeLocation         *Location              `protobuf:"bytes,3,opt,name=codeLocation,proto3" json:"codeLocation,omitempty"`
	LineNumber           *int64                 `protobuf:"varint,4,opt,name=LineNumber,proto3,oneof" json:"LineNumber,omitempty"`
	Variables            *structpb.Struct       `protobuf:"bytes,5,opt,name=variables,proto3" json:"variables,omitempty"`
	Links                []*ExternalLink        `protobuf:"bytes,6,rep,name=links,proto3" json:"links,omitempty"`
	IsDependencyIncident bool                   `protobuf:"varint,7,opt,name=IsDependencyIncident,proto3" json:"IsDependencyIncident,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *IncidentContext) Reset() {
	*x = IncidentContext{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncidentContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncidentContext) ProtoMessage() {}

func (x *IncidentContext) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncidentContext.ProtoReflect.Descriptor instead.
func (*IncidentContext) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{6}
}

func (x *IncidentContext) GetFileURI() string {
	if x != nil {
		return x.FileURI
	}
	return ""
}

func (x *IncidentContext) GetEffort() int64 {
	if x != nil && x.Effort != nil {
		return *x.Effort
	}
	return 0
}

func (x *IncidentContext) GetCodeLocation() *Location {
	if x != nil {
		return x.CodeLocation
	}
	return nil
}

func (x *IncidentContext) GetLineNumber() int64 {
	if x != nil && x.LineNumber != nil {
		return *x.LineNumber
	}
	return 0
}

func (x *IncidentContext) GetVariables() *structpb.Struct {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *IncidentContext) GetLinks() []*ExternalLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *IncidentContext) GetIsDependencyIncident() bool {
	if x != nil {
		return x.IsDependencyIncident
	}
	return false
}

type ProviderEvaluateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Matched          bool                   `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	IncidentContexts []*IncidentContext     `protobuf:"bytes,2,rep,name=incidentContexts,proto3" json:"incidentContexts,omitempty"`
	TemplateContext  *structpb.Struct       `protobuf:"bytes,3,opt,name=templateContext,proto3" json:"templateContext,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProviderEvaluateResponse) Reset() {
	*x = ProviderEvaluateResponse{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderEvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderEvaluateResponse) ProtoMessage() {}

func (x *ProviderEvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderEvaluateResponse.ProtoReflect.Descriptor instead.
func (*ProviderEvaluateResponse) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{7}
}

func (x *ProviderEvaluateResponse) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *ProviderEvaluateResponse) GetIncidentContexts() []*IncidentContext {
	if x != nil {
		return x.IncidentContexts
	}
	return nil
}

func (x *ProviderEvaluateResponse) GetTemplateContext() *structpb.Struct {
	if x != nil {
		return x.TemplateContext
	}
	return nil
}

type BasicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Successful    bool                   `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicResponse) Reset() {
	*x = BasicResponse{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicResponse) ProtoMessage() {}

func (x *BasicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicResponse.ProtoReflect.Descriptor instead.
func (*BasicResponse) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{8}
}

func (x *BasicResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BasicResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cap           string                 `protobuf:"bytes,1,opt,name=cap,proto3" json:"cap,omitempty"`
	ConditionInfo string                 `protobuf:"bytes,2,opt,name=conditionInfo,proto3" json:"conditionInfo,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{9}
}

func (x *EvaluateRequest) GetCap() string {
	if x != nil {
		return x.Cap
	}
	return ""
}

func (x *EvaluateRequest) GetConditionInfo() string {
	if x != nil {
		return x.ConditionInfo
	}
	return ""
}

func (x *EvaluateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EvaluateResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Error         string                    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Successful    bool                      `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	Response      *ProviderEvaluateResponse `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{10}
}

func (x *EvaluateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EvaluateResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *EvaluateResponse) GetResponse() *ProviderEvaluateResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type CapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []*Capability          `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{11}
}

func (x *CapabilitiesResponse) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRequest) Reset() {
	*x = ServiceRequest{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest) ProtoMessage() {}

func (x *ServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest.ProtoReflect.Descriptor instead.
func (*ServiceRequest) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{12}
}

func (x *ServiceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCodeSnipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	CodeLocation  *Location              `protobuf:"bytes,2,opt,name=codeLocation,proto3" json:"codeLocation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCodeSnipRequest) Reset() {
	*x = GetCodeSnipRequest{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCodeSnipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCodeSnipRequest) ProtoMessage() {}

func (x *GetCodeSnipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCodeSnipRequest.ProtoReflect.Descriptor instead.
func (*GetCodeSnipRequest) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{13}
}

func (x *GetCodeSnipRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *GetCodeSnipRequest) GetCodeLocation() *Location {
	if x != nil {
		return x.CodeLocation
	}
	return nil
}

type GetDependencyLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dep           *Dependency            `protobuf:"bytes,1,opt,name=dep,proto3" json:"dep,omitempty"`
	DepFile       string                 `protobuf:"bytes,2,opt,name=DepFile,proto3" json:"DepFile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDependencyLocationRequest) Reset() {
	*x = GetDependencyLocationRequest{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDependencyLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependencyLocationRequest) ProtoMessage() {}

func (x *GetDependencyLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependencyLocationRequest.ProtoReflect.Descriptor instead.
func (*GetDependencyLocationRequest) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{14}
}

func (x *GetDependencyLocationRequest) GetDep() *Dependency {
	if x != nil {
		return x.Dep
	}
	return nil
}

func (x *GetDependencyLocationRequest) GetDepFile() string {
	if x != nil {
		return x.DepFile
	}
	return ""
}

type GetCodeSnipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snip          string                 `protobuf:"bytes,1,opt,name=snip,proto3" json:"snip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCodeSnipResponse) Reset() {
	*x = GetCodeSnipResponse{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCodeSnipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCodeSnipResponse) ProtoMessage() {}

func (x *GetCodeSnipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCodeSnipResponse.ProtoReflect.Descriptor instead.
func (*GetCodeSnipResponse) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{15}
}

func (x *GetCodeSnipResponse) GetSnip() string {
	if x != nil {
		return x.Snip
	}
	return ""
}

type GetDependencyLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDependencyLocationResponse) Reset() {
	*x = GetDependencyLocationResponse{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDependencyLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependencyLocationResponse) ProtoMessage() {}

func (x *GetDependencyLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependencyLocationResponse.ProtoReflect.Descriptor instead.
func (*GetDependencyLocationResponse) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{16}
}

func (x *GetDependencyLocationResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type Dependency struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version            string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Classifier         string                 `protobuf:"bytes,3,opt,name=classifier,proto3" json:"classifier,omitempty"`
	Type               string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ResolvedIdentifier string                 `protobuf:"bytes,5,opt,name=resolvedIdentifier,proto3" json:"resolvedIdentifier,omitempty"`
	FileURIPrefix      string                 `protobuf:"bytes,6,opt,name=fileURIPrefix,proto3" json:"fileURIPrefix,omitempty"`
	Indirect           bool                   `protobuf:"varint,7,opt,name=indirect,proto3" json:"indirect,omitempty"`
	Extras             *structpb.Struct       `protobuf:"bytes,8,opt,name=extras,proto3" json:"extras,omitempty"`
	Labels             []string               `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{17}
}

func (x *Dependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Dependency) GetClassifier() string {
	if x != nil {
		return x.Classifier
	}
	return ""
}

func (x *Dependency) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Dependency) GetResolvedIdentifier() string {
	if x != nil {
		return x.ResolvedIdentifier
	}
	return ""
}

func (x *Dependency) GetFileURIPrefix() string {
	if x != nil {
		return x.FileURIPrefix
	}
	return ""
}

func (x *Dependency) GetIndirect() bool {
	if x != nil {
		return x.Indirect
	}
	return false
}

func (x *Dependency) GetExtras() *structpb.Struct {
	if x != nil {
		return x.Extras
	}
	return nil
}

func (x *Dependency) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type DependencyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deps          []*Dependency          `protobuf:"bytes,1,rep,name=deps,proto3" json:"deps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyList) Reset() {
	*x = DependencyList{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyList) ProtoMessage() {}

func (x *DependencyList) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyList.ProtoReflect.Descriptor instead.
func (*DependencyList) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{18}
}

func (x *DependencyList) GetDeps() []*Dependency {
	if x != nil {
		return x.Deps
	}
	return nil
}

type DependencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successful    bool                   `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	FileDep       []*FileDep             `protobuf:"bytes,3,rep,name=fileDep,proto3" json:"fileDep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyResponse) Reset() {
	*x = DependencyResponse{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyResponse) ProtoMessage() {}

func (x *DependencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyResponse.ProtoReflect.Descriptor instead.
func (*DependencyResponse) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{19}
}

func (x *DependencyResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *DependencyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DependencyResponse) GetFileDep() []*FileDep {
	if x != nil {
		return x.FileDep
	}
	return nil
}

type FileDep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileURI       string                 `protobuf:"bytes,3,opt,name=fileURI,proto3" json:"fileURI,omitempty"`
	List          *DependencyList        `protobuf:"bytes,4,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDep) Reset() {
	*x = FileDep{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDep) ProtoMessage() {}

func (x *FileDep) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDep.ProtoReflect.Descriptor instead.
func (*FileDep) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{20}
}

func (x *FileDep) GetFileURI() string {
	if x != nil {
		return x.FileURI
	}
	return ""
}

func (x *FileDep) GetList() *DependencyList {
	if x != nil {
		return x.List
	}
	return nil
}

type DependencyDAGItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Dependency            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	AddedDeps     []*DependencyDAGItem   `protobuf:"bytes,2,rep,name=addedDeps,proto3" json:"addedDeps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyDAGItem) Reset() {
	*x = DependencyDAGItem{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyDAGItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyDAGItem) ProtoMessage() {}

func (x *DependencyDAGItem) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyDAGItem.ProtoReflect.Descriptor instead.
func (*DependencyDAGItem) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{21}
}

func (x *DependencyDAGItem) GetKey() *Dependency {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DependencyDAGItem) GetAddedDeps() []*DependencyDAGItem {
	if x != nil {
		return x.AddedDeps
	}
	return nil
}

type DependencyDAGResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successful    bool                   `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	FileDagDep    []*FileDAGDep          `protobuf:"bytes,3,rep,name=fileDagDep,proto3" json:"fileDagDep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyDAGResponse) Reset() {
	*x = DependencyDAGResponse{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyDAGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyDAGResponse) ProtoMessage() {}

func (x *DependencyDAGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyDAGResponse.ProtoReflect.Descriptor instead.
func (*DependencyDAGResponse) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{22}
}

func (x *DependencyDAGResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *DependencyDAGResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DependencyDAGResponse) GetFileDagDep() []*FileDAGDep {
	if x != nil {
		return x.FileDagDep
	}
	return nil
}

type FileDAGDep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileURI       string                 `protobuf:"bytes,3,opt,name=fileURI,proto3" json:"fileURI,omitempty"`
	List          []*DependencyDAGItem   `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDAGDep) Reset() {
	*x = FileDAGDep{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDAGDep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDAGDep) ProtoMessage() {}

func (x *FileDAGDep) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDAGDep.ProtoReflect.Descriptor instead.
func (*FileDAGDep) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{23}
}

func (x *FileDAGDep) GetFileURI() string {
	if x != nil {
		return x.FileURI
	}
	return ""
}

func (x *FileDAGDep) GetList() []*DependencyDAGItem {
	if x != nil {
		return x.List
	}
	return nil
}

type Proxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HTTPProxy     string                 `protobuf:"bytes,1,opt,name=HTTPProxy,proto3" json:"HTTPProxy,omitempty"`
	HTTPSProxy    string                 `protobuf:"bytes,2,opt,name=HTTPSProxy,proto3" json:"HTTPSProxy,omitempty"`
	NoProxy       string                 `protobuf:"bytes,3,opt,name=NoProxy,proto3" json:"NoProxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proxy) Reset() {
	*x = Proxy{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proxy) ProtoMessage() {}

func (x *Proxy) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proxy.ProtoReflect.Descriptor instead.
func (*Proxy) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{24}
}

func (x *Proxy) GetHTTPProxy() string {
	if x != nil {
		return x.HTTPProxy
	}
	return ""
}

func (x *Proxy) GetHTTPSProxy() string {
	if x != nil {
		return x.HTTPSProxy
	}
	return ""
}

func (x *Proxy) GetNoProxy() string {
	if x != nil {
		return x.NoProxy
	}
	return ""
}

type FileChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=Uri,proto3" json:"Uri,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	Saved         bool                   `protobuf:"varint,3,opt,name=Saved,proto3" json:"Saved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChange) Reset() {
	*x = FileChange{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChange) ProtoMessage() {}

func (x *FileChange) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChange.ProtoReflect.Descriptor instead.
func (*FileChange) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{25}
}

func (x *FileChange) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *FileChange) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FileChange) GetSaved() bool {
	if x != nil {
		return x.Saved
	}
	return false
}

type NotifyFileChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*FileChange          `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyFileChangesRequest) Reset() {
	*x = NotifyFileChangesRequest{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyFileChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyFileChangesRequest) ProtoMessage() {}

func (x *NotifyFileChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyFileChangesRequest.ProtoReflect.Descriptor instead.
func (*NotifyFileChangesRequest) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{26}
}

func (x *NotifyFileChangesRequest) GetChanges() []*FileChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *NotifyFileChangesRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NotifyFileChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyFileChangesResponse) Reset() {
	*x = NotifyFileChangesResponse{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyFileChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyFileChangesResponse) ProtoMessage() {}

func (x *NotifyFileChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyFileChangesResponse.ProtoReflect.Descriptor instead.
func (*NotifyFileChangesResponse) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{27}
}

func (x *NotifyFileChangesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConditionsByCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cap           string                 `protobuf:"bytes,1,opt,name=cap,proto3" json:"cap,omitempty"`
	ConditionInfo []string               `protobuf:"bytes,2,rep,name=conditionInfo,proto3" json:"conditionInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionsByCapability) Reset() {
	*x = ConditionsByCapability{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionsByCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionsByCapability) ProtoMessage() {}

func (x *ConditionsByCapability) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionsByCapability.ProtoReflect.Descriptor instead.
func (*ConditionsByCapability) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{28}
}

func (x *ConditionsByCapability) GetCap() string {
	if x != nil {
		return x.Cap
	}
	return ""
}

func (x *ConditionsByCapability) GetConditionInfo() []string {
	if x != nil {
		return x.ConditionInfo
	}
	return nil
}

type PrepareRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Conditions    []*ConditionsByCapability `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Id            int64                     `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{29}
}

func (x *PrepareRequest) GetConditions() []*ConditionsByCapability {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *PrepareRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PrepareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{30}
}

func (x *PrepareResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PrepareProgressEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProviderName   string                 `protobuf:"bytes,1,opt,name=providerName,proto3" json:"providerName,omitempty"`
	FilesProcessed int32                  `protobuf:"varint,2,opt,name=filesProcessed,proto3" json:"filesProcessed,omitempty"`
	TotalFiles     int32                  `protobuf:"varint,3,opt,name=totalFiles,proto3" json:"totalFiles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrepareProgressEvent) Reset() {
	*x = PrepareProgressEvent{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareProgressEvent) ProtoMessage() {}

func (x *PrepareProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareProgressEvent.ProtoReflect.Descriptor instead.
func (*PrepareProgressEvent) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{31}
}

func (x *PrepareProgressEvent) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *PrepareProgressEvent) GetFilesProcessed() int32 {
	if x != nil {
		return x.FilesProcessed
	}
	return 0
}

func (x *PrepareProgressEvent) GetTotalFiles() int32 {
	if x != nil {
		return x.TotalFiles
	}
	return 0
}

type PrepareProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareProgressRequest) Reset() {
	*x = PrepareProgressRequest{}
	mi := &file_provider_internal_grpc_library_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareProgressRequest) ProtoMessage() {}

func (x *PrepareProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_internal_grpc_library_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareProgressRequest.ProtoReflect.Descriptor instead.
func (*PrepareProgressRequest) Descriptor() ([]byte, []int) {
	return file_provider_internal_grpc_library_proto_rawDescGZIP(), []int{32}
}

func (x *PrepareProgressRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_provider_internal_grpc_library_proto protoreflect.FileDescriptor

const file_provider_internal_grpc_library_proto_rawDesc = "" +
	"\n" +
	"$provider/internal/grpc/library.proto\x12\bprovider\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"c\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12A\n" +
	"\x0ftemplateContext\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x0ftemplateContext\"\xba\x02\n" +
	"\x06Config\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12&\n" +
	"\x0edependencyPath\x18\x02 \x01(\tR\x0edependencyPath\x12\"\n" +
	"\fanalysisMode\x18\x04 \x01(\tR\fanalysisMode\x12O\n" +
	"\x16providerSpecificConfig\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x16providerSpecificConfig\x12%\n" +
	"\x05proxy\x18\x06 \x01(\v2\x0f.provider.ProxyR\x05proxy\x12.\n" +
	"\x12languageServerPipe\x18\a \x01(\tR\x12languageServerPipe\x12 \n" +
	"\vinitialized\x18\b \x01(\bR\vinitialized\"\x8c\x01\n" +
	"\fInitResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x1e\n" +
	"\n" +
	"successful\x18\x02 \x01(\bR\n" +
	"successful\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x126\n" +
	"\rbuiltinConfig\x18\x04 \x01(\v2\x10.provider.ConfigR\rbuiltinConfig\"6\n" +
	"\fExternalLink\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"<\n" +
	"\bPosition\x12\x12\n" +
	"\x04line\x18\x01 \x01(\x01R\x04line\x12\x1c\n" +
	"\tcharacter\x18\x02 \x01(\x01R\tcharacter\"z\n" +
	"\bLocation\x128\n" +
	"\rstartPosition\x18\x01 \x01(\v2\x12.provider.PositionR\rstartPosition\x124\n" +
	"\vendPosition\x18\x02 \x01(\v2\x12.provider.PositionR\vendPosition\"\xd8\x02\n" +
	"\x0fIncidentContext\x12\x18\n" +
	"\afileURI\x18\x01 \x01(\tR\afileURI\x12\x1b\n" +
	"\x06Effort\x18\x02 \x01(\x03H\x00R\x06Effort\x88\x01\x01\x126\n" +
	"\fcodeLocation\x18\x03 \x01(\v2\x12.provider.LocationR\fcodeLocation\x12#\n" +
	"\n" +
	"LineNumber\x18\x04 \x01(\x03H\x01R\n" +
	"LineNumber\x88\x01\x01\x125\n" +
	"\tvariables\x18\x05 \x01(\v2\x17.google.protobuf.StructR\tvariables\x12,\n" +
	"\x05links\x18\x06 \x03(\v2\x16.provider.ExternalLinkR\x05links\x122\n" +
	"\x14IsDependencyIncident\x18\a \x01(\bR\x14IsDependencyIncidentB\t\n" +
	"\a_EffortB\r\n" +
	"\v_LineNumber\"\xbe\x01\n" +
	"\x18ProviderEvaluateResponse\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched\x12E\n" +
	"\x10incidentContexts\x18\x02 \x03(\v2\x19.provider.IncidentContextR\x10incidentContexts\x12A\n" +
	"\x0ftemplateContext\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0ftemplateContext\"E\n" +
	"\rBasicResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x1e\n" +
	"\n" +
	"successful\x18\x02 \x01(\bR\n" +
	"successful\"Y\n" +
	"\x0fEvaluateRequest\x12\x10\n" +
	"\x03cap\x18\x01 \x01(\tR\x03cap\x12$\n" +
	"\rconditionInfo\x18\x02 \x01(\tR\rconditionInfo\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\"\x88\x01\n" +
	"\x10EvaluateResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x1e\n" +
	"\n" +
	"successful\x18\x02 \x01(\bR\n" +
	"successful\x12>\n" +
	"\bresponse\x18\x03 \x01(\v2\".provider.ProviderEvaluateResponseR\bresponse\"P\n" +
	"\x14CapabilitiesResponse\x128\n" +
	"\fcapabilities\x18\x01 \x03(\v2\x14.provider.CapabilityR\fcapabilities\" \n" +
	"\x0eServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"^\n" +
	"\x12GetCodeSnipRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x126\n" +
	"\fcodeLocation\x18\x02 \x01(\v2\x12.provider.LocationR\fcodeLocation\"`\n" +
	"\x1cGetDependencyLocationRequest\x12&\n" +
	"\x03dep\x18\x01 \x01(\v2\x14.provider.DependencyR\x03dep\x12\x18\n" +
	"\aDepFile\x18\x02 \x01(\tR\aDepFile\")\n" +
	"\x13GetCodeSnipResponse\x12\x12\n" +
	"\x04snip\x18\x01 \x01(\tR\x04snip\"O\n" +
	"\x1dGetDependencyLocationResponse\x12.\n" +
	"\blocation\x18\x01 \x01(\v2\x12.provider.LocationR\blocation\"\xa9\x02\n" +
	"\n" +
	"Dependency\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1e\n" +
	"\n" +
	"classifier\x18\x03 \x01(\tR\n" +
	"classifier\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12.\n" +
	"\x12resolvedIdentifier\x18\x05 \x01(\tR\x12resolvedIdentifier\x12$\n" +
	"\rfileURIPrefix\x18\x06 \x01(\tR\rfileURIPrefix\x12\x1a\n" +
	"\bindirect\x18\a \x01(\bR\bindirect\x12/\n" +
	"\x06extras\x18\b \x01(\v2\x17.google.protobuf.StructR\x06extras\x12\x16\n" +
	"\x06labels\x18\t \x03(\tR\x06labels\":\n" +
	"\x0eDependencyList\x12(\n" +
	"\x04deps\x18\x01 \x03(\v2\x14.provider.DependencyR\x04deps\"w\n" +
	"\x12DependencyResponse\x12\x1e\n" +
	"\n" +
	"successful\x18\x01 \x01(\bR\n" +
	"successful\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12+\n" +
	"\afileDep\x18\x03 \x03(\v2\x11.provider.FileDepR\afileDep\"Q\n" +
	"\aFileDep\x12\x18\n" +
	"\afileURI\x18\x03 \x01(\tR\afileURI\x12,\n" +
	"\x04list\x18\x04 \x01(\v2\x18.provider.DependencyListR\x04list\"v\n" +
	"\x11DependencyDAGItem\x12&\n" +
	"\x03key\x18\x01 \x01(\v2\x14.provider.DependencyR\x03key\x129\n" +
	"\taddedDeps\x18\x02 \x03(\v2\x1b.provider.DependencyDAGItemR\taddedDeps\"\x83\x01\n" +
	"\x15DependencyDAGResponse\x12\x1e\n" +
	"\n" +
	"successful\x18\x01 \x01(\bR\n" +
	"successful\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x124\n" +
	"\n" +
	"fileDagDep\x18\x03 \x03(\v2\x14.provider.FileDAGDepR\n" +
	"fileDagDep\"W\n" +
	"\n" +
	"FileDAGDep\x12\x18\n" +
	"\afileURI\x18\x03 \x01(\tR\afileURI\x12/\n" +
	"\x04list\x18\x04 \x03(\v2\x1b.provider.DependencyDAGItemR\x04list\"_\n" +
	"\x05Proxy\x12\x1c\n" +
	"\tHTTPProxy\x18\x01 \x01(\tR\tHTTPProxy\x12\x1e\n" +
	"\n" +
	"HTTPSProxy\x18\x02 \x01(\tR\n" +
	"HTTPSProxy\x12\x18\n" +
	"\aNoProxy\x18\x03 \x01(\tR\aNoProxy\"N\n" +
	"\n" +
	"FileChange\x12\x10\n" +
	"\x03Uri\x18\x01 \x01(\tR\x03Uri\x12\x18\n" +
	"\aContent\x18\x02 \x01(\tR\aContent\x12\x14\n" +
	"\x05Saved\x18\x03 \x01(\bR\x05Saved\"Z\n" +
	"\x18NotifyFileChangesRequest\x12.\n" +
	"\achanges\x18\x01 \x03(\v2\x14.provider.FileChangeR\achanges\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"1\n" +
	"\x19NotifyFileChangesResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"P\n" +
	"\x16ConditionsByCapability\x12\x10\n" +
	"\x03cap\x18\x01 \x01(\tR\x03cap\x12$\n" +
	"\rconditionInfo\x18\x02 \x03(\tR\rconditionInfo\"b\n" +
	"\x0ePrepareRequest\x12@\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2 .provider.ConditionsByCapabilityR\n" +
	"conditions\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"'\n" +
	"\x0fPrepareResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x82\x01\n" +
	"\x14PrepareProgressEvent\x12\"\n" +
	"\fproviderName\x18\x01 \x01(\tR\fproviderName\x12&\n" +
	"\x0efilesProcessed\x18\x02 \x01(\x05R\x0efilesProcessed\x12\x1e\n" +
	"\n" +
	"totalFiles\x18\x03 \x01(\x05R\n" +
	"totalFiles\"(\n" +
	"\x16PrepareProgressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2k\n" +
	"\x1bProviderCodeLocationService\x12L\n" +
	"\vGetCodeSnip\x12\x1c.provider.GetCodeSnipRequest\x1a\x1d.provider.GetCodeSnipResponse\"\x002\x8f\x01\n" +
	"!ProviderDependencyLocationService\x12j\n" +
	"\x15GetDependencyLocation\x12&.provider.GetDependencyLocationRequest\x1a'.provider.GetDependencyLocationResponse\"\x002\xb1\x05\n" +
	"\x0fProviderService\x12H\n" +
	"\fCapabilities\x12\x16.google.protobuf.Empty\x1a\x1e.provider.CapabilitiesResponse\"\x00\x122\n" +
	"\x04Init\x12\x10.provider.Config\x1a\x16.provider.InitResponse\"\x00\x12C\n" +
	"\bEvaluate\x12\x19.provider.EvaluateRequest\x1a\x1a.provider.EvaluateResponse\"\x00\x12:\n" +
	"\x04Stop\x12\x18.provider.ServiceRequest\x1a\x16.google.protobuf.Empty\"\x00\x12K\n" +
	"\x0fGetDependencies\x12\x18.provider.ServiceRequest\x1a\x1c.provider.DependencyResponse\"\x00\x12Q\n" +
	"\x12GetDependenciesDAG\x12\x18.provider.ServiceRequest\x1a\x1f.provider.DependencyDAGResponse\"\x00\x12^\n" +
	"\x11NotifyFileChanges\x12\".provider.NotifyFileChangesRequest\x1a#.provider.NotifyFileChangesResponse\"\x00\x12@\n" +
	"\aPrepare\x12\x18.provider.PrepareRequest\x1a\x19.provider.PrepareResponse\"\x00\x12]\n" +
	"\x15StreamPrepareProgress\x12 .provider.PrepareProgressRequest\x1a\x1e.provider.PrepareProgressEvent\"\x000\x01B4Z2github.com/konveyor/analyzer-lsp/provider/lib/grpcb\x06proto3"

var (
	file_provider_internal_grpc_library_proto_rawDescOnce sync.Once
	file_provider_internal_grpc_library_proto_rawDescData []byte
)

func file_provider_internal_grpc_library_proto_rawDescGZIP() []byte {
	file_provider_internal_grpc_library_proto_rawDescOnce.Do(func() {
		file_provider_internal_grpc_library_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_internal_grpc_library_proto_rawDesc), len(file_provider_internal_grpc_library_proto_rawDesc)))
	})
	return file_provider_internal_grpc_library_proto_rawDescData
}

var file_provider_internal_grpc_library_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_provider_internal_grpc_library_proto_goTypes = []any{
	(*Capability)(nil),                    // 0: provider.Capability
	(*Config)(nil),                        // 1: provider.Config
	(*InitResponse)(nil),                  // 2: provider.InitResponse
	(*ExternalLink)(nil),                  // 3: provider.ExternalLink
	(*Position)(nil),                      // 4: provider.Position
	(*Location)(nil),                      // 5: provider.Location
	(*IncidentContext)(nil),               // 6: provider.IncidentContext
	(*ProviderEvaluateResponse)(nil),      // 7: provider.ProviderEvaluateResponse
	(*BasicResponse)(nil),                 // 8: provider.BasicResponse
	(*EvaluateRequest)(nil),               // 9: provider.EvaluateRequest
	(*EvaluateResponse)(nil),              // 10: provider.EvaluateResponse
	(*CapabilitiesResponse)(nil),          // 11: provider.CapabilitiesResponse
	(*ServiceRequest)(nil),                // 12: provider.ServiceRequest
	(*GetCodeSnipRequest)(nil),            // 13: provider.GetCodeSnipRequest
	(*GetDependencyLocationRequest)(nil),  // 14: provider.GetDependencyLocationRequest
	(*GetCodeSnipResponse)(nil),           // 15: provider.GetCodeSnipResponse
	(*GetDependencyLocationResponse)(nil), // 16: provider.GetDependencyLocationResponse
	(*Dependency)(nil),                    // 17: provider.Dependency
	(*DependencyList)(nil),                // 18: provider.DependencyList
	(*DependencyResponse)(nil),            // 19: provider.DependencyResponse
	(*FileDep)(nil),                       // 20: provider.FileDep
	(*DependencyDAGItem)(nil),             // 21: provider.DependencyDAGItem
	(*DependencyDAGResponse)(nil),         // 22: provider.DependencyDAGResponse
	(*FileDAGDep)(nil),                    // 23: provider.FileDAGDep
	(*Proxy)(nil),                         // 24: provider.Proxy
	(*FileChange)(nil),                    // 25: provider.FileChange
	(*NotifyFileChangesRequest)(nil),      // 26: provider.NotifyFileChangesRequest
	(*NotifyFileChangesResponse)(nil),     // 27: provider.NotifyFileChangesResponse
	(*ConditionsByCapability)(nil),        // 28: provider.ConditionsByCapability
	(*PrepareRequest)(nil),                // 29: provider.PrepareRequest
	(*PrepareResponse)(nil),               // 30: provider.PrepareResponse
	(*PrepareProgressEvent)(nil),          // 31: provider.PrepareProgressEvent
	(*PrepareProgressRequest)(nil),        // 32: provider.PrepareProgressRequest
	(*structpb.Struct)(nil),               // 33: google.protobuf.Struct
	(*emptypb.Empty)(nil),                 // 34: google.protobuf.Empty
}
var file_provider_internal_grpc_library_proto_depIdxs = []int32{
	33, // 0: provider.Capability.templateContext:type_name -> google.protobuf.Struct
	33, // 1: provider.Config.providerSpecificConfig:type_name -> google.protobuf.Struct
	24, // 2: provider.Config.proxy:type_name -> provider.Proxy
	1,  // 3: provider.InitResponse.builtinConfig:type_name -> provider.Config
	4,  // 4: provider.Location.startPosition:type_name -> provider.Position
	4,  // 5: provider.Location.endPosition:type_name -> provider.Position
	5,  // 6: provider.IncidentContext.codeLocation:type_name -> provider.Location
	33, // 7: provider.IncidentContext.variables:type_name -> google.protobuf.Struct
	3,  // 8: provider.IncidentContext.links:type_name -> provider.ExternalLink
	6,  // 9: provider.ProviderEvaluateResponse.incidentContexts:type_name -> provider.IncidentContext
	33, // 10: provider.ProviderEvaluateResponse.templateContext:type_name -> google.protobuf.Struct
	7,  // 11: provider.EvaluateResponse.response:type_name -> provider.ProviderEvaluateResponse
	0,  // 12: provider.CapabilitiesResponse.capabilities:type_name -> provider.Capability
	5,  // 13: provider.GetCodeSnipRequest.codeLocation:type_name -> provider.Location
	17, // 14: provider.GetDependencyLocationRequest.dep:type_name -> provider.Dependency
	5,  // 15: provider.GetDependencyLocationResponse.location:type_name -> provider.Location
	33, // 16: provider.Dependency.extras:type_name -> google.protobuf.Struct
	17, // 17: provider.DependencyList.deps:type_name -> provider.Dependency
	20, // 18: provider.DependencyResponse.fileDep:type_name -> provider.FileDep
	18, // 19: provider.FileDep.list:type_name -> provider.DependencyList
	17, // 20: provider.DependencyDAGItem.key:type_name -> provider.Dependency
	21, // 21: provider.DependencyDAGItem.addedDeps:type_name -> provider.DependencyDAGItem
	23, // 22: provider.DependencyDAGResponse.fileDagDep:type_name -> provider.FileDAGDep
	21, // 23: provider.FileDAGDep.list:type_name -> provider.DependencyDAGItem
	25, // 24: provider.NotifyFileChangesRequest.changes:type_name -> provider.FileChange
	28, // 25: provider.PrepareRequest.conditions:type_name -> provider.ConditionsByCapability
	13, // 26: provider.ProviderCodeLocationService.GetCodeSnip:input_type -> provider.GetCodeSnipRequest
	14, // 27: provider.ProviderDependencyLocationService.GetDependencyLocation:input_type -> provider.GetDependencyLocationRequest
	34, // 28: provider.ProviderService.Capabilities:input_type -> google.protobuf.Empty
	1,  // 29: provider.ProviderService.Init:input_type -> provider.Config
	9,  // 30: provider.ProviderService.Evaluate:input_type -> provider.EvaluateRequest
	12, // 31: provider.ProviderService.Stop:input_type -> provider.ServiceRequest
	12, // 32: provider.ProviderService.GetDependencies:input_type -> provider.ServiceRequest
	12, // 33: provider.ProviderService.GetDependenciesDAG:input_type -> provider.ServiceRequest
	26, // 34: provider.ProviderService.NotifyFileChanges:input_type -> provider.NotifyFileChangesRequest
	29, // 35: provider.ProviderService.Prepare:input_type -> provider.PrepareRequest
	32, // 36: provider.ProviderService.StreamPrepareProgress:input_type -> provider.PrepareProgressRequest
	15, // 37: provider.ProviderCodeLocationService.GetCodeSnip:output_type -> provider.GetCodeSnipResponse
	16, // 38: provider.ProviderDependencyLocationService.GetDependencyLocation:output_type -> provider.GetDependencyLocationResponse
	11, // 39: provider.ProviderService.Capabilities:output_type -> provider.CapabilitiesResponse
	2,  // 40: provider.ProviderService.Init:output_type -> provider.InitResponse
	10, // 41: provider.ProviderService.Evaluate:output_type -> provider.EvaluateResponse
	34, // 42: provider.ProviderService.Stop:output_type -> google.protobuf.Empty
	19, // 43: provider.ProviderService.GetDependencies:output_type -> provider.DependencyResponse
	22, // 44: provider.ProviderService.GetDependenciesDAG:output_type -> provider.DependencyDAGResponse
	27, // 45: provider.ProviderService.NotifyFileChanges:output_type -> provider.NotifyFileChangesResponse
	30, // 46: provider.ProviderService.Prepare:output_type -> provider.PrepareResponse
	31, // 47: provider.ProviderService.StreamPrepareProgress:output_type -> provider.PrepareProgressEvent
	37, // [37:48] is the sub-list for method output_type
	26, // [26:37] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_provider_internal_grpc_library_proto_init() }
func file_provider_internal_grpc_library_proto_init() {
	if File_provider_internal_grpc_library_proto != nil {
		return
	}
	file_provider_internal_grpc_library_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_internal_grpc_library_proto_rawDesc), len(file_provider_internal_grpc_library_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_provider_internal_grpc_library_proto_goTypes,
		DependencyIndexes: file_provider_internal_grpc_library_proto_depIdxs,
		MessageInfos:      file_provider_internal_grpc_library_proto_msgTypes,
	}.Build()
	File_provider_internal_grpc_library_proto = out.File
	file_provider_internal_grpc_library_proto_goTypes = nil
	file_provider_internal_grpc_library_proto_depIdxs = nil
}
