FROM golang:1.21-windowsservercore-ltsc2022 as builder

COPY / /analyzer-lsp
WORKDIR /dotnet-provider

COPY external-providers/dotnet-external-provider/Makefile .
COPY external-providers/dotnet-external-provider/go.mod .
COPY external-providers/dotnet-external-provider/go.sum .
COPY external-providers/dotnet-external-provider/main.go .
COPY external-providers/dotnet-external-provider/pkg/ ./pkg

RUN go mod edit --replace=github.com/konveyor/analyzer-lsp=C:\analyzer-lsp
RUN go mod tidy

RUN go build -o bin/dotnet-external-provider.exe main.go

FROM mcr.microsoft.com/dotnet/framework/sdk:9.0

RUN dotnet tool install --global csharp-ls --version 0.17.0

# Set the working directory inside the container
WORKDIR C:/app

# Copy the executable from the builder stage
COPY --from=builder /dotnet-provider/bin/dotnet-external-provider.exe .
EXPOSE 3456

# Command to run the executable
ENTRYPOINT ["dotnet-external-provider.exe", "-port", "3456"]
