name: Run benchmark tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ${{ matrix.os.id }}

    strategy:
      matrix:
        os:
        - id: macos-latest
          name: mac

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run benchmark tests
      run: |
        go install golang.org/x/perf/cmd/benchstat@latest
        go mod tidy
        go test -run=^$ -bench=. -benchmem -count=6 ./... > benchmark_results

    - name: Display Benchstat results
      run: benchstat benchmark.${{ matrix.os.name }} benchmark_results
